oc_pizzeria_home:
    path:      /pizzeria
    defaults: { _controller: OCPlatformBundle:Accueil:menu }
    

oc_pizzeria_ingredient_index:
    path:      /pizzeria/ingredient/
    defaults: { _controller: OCPlatformBundle:Ingredient:index }

oc_pizzeria_ingredient_add:
    path:      /pizzeria/ingredient/add/
    defaults: { _controller: OCPlatformBundle:Ingredient:add }

oc_pizzeria_ingredient_edit:
    path:      /pizzeria/ingredient/edit/{id}
    defaults: { _controller: OCPlatformBundle:Ingredient:edit }
    

    
oc_pizzeria_gamme_add:
    path:      /pizzeria/gamme/add/
    defaults: { _controller: OCPlatformBundle:Gamme:add }
    
oc_pizzeria_gamme_index:
    path:      /pizzeria/gamme/
    defaults: { _controller: OCPlatformBundle:Gamme:index }
    
oc_pizzeria_gamme_edit:
    path:      /pizzeria/gamme/edit/{id}
    defaults: { _controller: OCPlatformBundle:Gamme:edit }




oc_pizzeria_produit_index:
    path:      /pizzeria/produit/
    defaults: { _controller: OCPlatformBundle:Produit:index }
    
oc_pizzeria_produit_add:
    path:      /pizzeria/produit/add/
    defaults: { _controller: OCPlatformBundle:Produit:add }
    
oc_pizzeria_produit_edit:
    path:      /pizzeria/produit/edit/{id}
    defaults: { _controller: OCPlatformBundle:Produit:edit }