<<<<<<< HEAD
oc_pizzeria_home:
    path:      /pizzeria
    defaults: { _controller: OCPlatformBundle:Accueil:index }
    

=======
>>>>>>> user
oc_pizzeria_ingredient_index:
    path:      /pizzeria/ingredient/
    defaults: { _controller: OCPlatformBundle:Ingredient:index }

oc_pizzeria_ingredient_add:
    path:      /pizzeria/ingredient/add/
    defaults: { _controller: OCPlatformBundle:Ingredient:add }

oc_pizzeria_ingredient_edit:
    path:      /pizzeria/ingredient/edit/{id}
    defaults: { _controller: OCPlatformBundle:Ingredient:edit }
    

    
oc_pizzeria_gamme_add:
    path:      /pizzeria/gamme/add/
    defaults: { _controller: OCPlatformBundle:Gamme:add }
    
oc_pizzeria_gamme_index:
    path:      /pizzeria/gamme/
    defaults: { _controller: OCPlatformBundle:Gamme:index }
    
oc_pizzeria_gamme_edit:
    path:      /pizzeria/gamme/edit/{id}
    defaults: { _controller: OCPlatformBundle:Gamme:edit }
    
oc_pizzeria_gamme_view:
    path:      /pizzeria/gamme/view/{id}
    defaults: { _controller: OCPlatformBundle:Gamme:view }



oc_pizzeria_produit_index:
    path:      /pizzeria/produit/
    defaults: { _controller: OCPlatformBundle:Produit:index }
    
oc_pizzeria_produit_add:
    path:      /pizzeria/produit/add/
    defaults: { _controller: OCPlatformBundle:Produit:add }
    
oc_pizzeria_produit_edit:
    path:      /pizzeria/produit/edit/{id}
    defaults: { _controller: OCPlatformBundle:Produit:edit }
    
oc_pizzeria_produit_view:
    path:      /pizzeria/produit/view/{id}
    defaults: { _controller: OCPlatformBundle:Produit:view }
    
    
    
oc_pizzeria_panier_index:
    path:      /pizzeria/panier/
    defaults: { _controller: OCPlatformBundle:Panier:index }
    
oc_pizzeria_panier_new:
    path:      /pizzeria/panier/new
    defaults: { _controller: OCPlatformBundle:Panier:new }
    
oc_pizzeria_panier_show:
    path:      /pizzeria/panier/show
    defaults: { _controller: OCPlatformBundle:Panier:show }
  
oc_pizzeria_panier_add:
    path:      /pizzeria/panier/add/{idproduit}
    defaults: { _controller: OCPlatformBundle:Panier:addToPanier }