oc_pizzeria_home:
    path:      /pizzeria
    defaults: { _controller: OCPlatformBundle:Accueil:menu }
    
oc_pizzeria_ingredient:
    path:      /pizzeria/advert/menu
    defaults: { _controller: OCPlatformBundle:Accueil:menu }

