oc_pizzeria_ingredient_index:
    path:      /pizzeria/ingredient/
    defaults: { _controller: OCPlatformBundle:Ingredient:index }

oc_pizzeria_ingredient_add:
    path:      /pizzeria/ingredient/add/
    defaults: { _controller: OCPlatformBundle:Ingredient:add }

oc_pizzeria_ingredient_edit:
    path:      /pizzeria/ingredient/edit/{id}
    defaults: { _controller: OCPlatformBundle:Ingredient:edit }
    
oc_pizzeria_ingredient_index:
    path:      /pizzeria/gamme/
    defaults: { _controller: OCPlatformBundle:Gamme:index }
    
oc_pizzeria_gamme_add:
    path:      /pizzeria/gamme/add/
    defaults: { _controller: OCPlatformBundle:Gamme:add }
    
oc_pizzeria_gamme_index:
    path:      /pizzeria/gamme/
    defaults: { _controller: OCPlatformBundle:Gamme:index }
    
oc_pizzeria_gamme_edit:
    path:      /pizzeria/ingredient/edit/{id}
    defaults: { _controller: OCPlatformBundle:Gamme:edit }